# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario_Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='itinerario',
            name='calificacion_general',
            field=models.CharField(choices=[(b'1', b'Malo'), (b'2', b'Regular'), (b'3', b'Bueno'), (b'4', b'Muy bueno'), (b'5', b'Excelente')], default=b'3', max_length=2),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_10',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_11',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_12',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_13',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_14',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_15',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_16',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_17',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_18',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_19',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_20',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='dia_9',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='fecha_llegada',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerario',
            name='fecha_salida',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerario',
            name='pais_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Pais'),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='foto_general',
            field=models.ImageField(default=b'sitio/imagenes/none/no-img.png', upload_to=b'sitio/imagenes/'),
        ),
    ]
