# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='pais_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Pais'),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='foto_general',
            field=models.ImageField(default='sitio/imagenes/none/no-img.png', upload_to='sitio/imagenes/'),
        ),
    ]
