# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_localidad_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='calificacion',
            field=models.CharField(choices=[('Malo', 'Malo'), ('Regular', 'Regular'), ('Bueno', 'Bueno'), ('Muy Bueno', 'Muy Bueno'), ('Excelente', 'Excelente')], default='3', max_length=9),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=500),
        ),
    ]
