# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0003_remove_itinerario_calificacion_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Itinerario_Dias',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_1',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_10',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_11',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_12',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_13',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_14',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_15',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_16',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_17',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_18',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_19',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_2',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_20',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_3',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_4',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_5',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_6',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_7',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_8',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='dia_9',
        ),
        migrations.AddField(
            model_name='itinerario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dia',
            name='itinerario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Itinerario'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Estado'),
        ),
    ]
