# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_auto_20170516_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
