# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_auto_20170519_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
