# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_auto_20170520_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='denuncias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
    ]
