# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_auto_20170521_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='foto_dia',
            field=models.ImageField(default='/static/sitio/imagenes/turismo_noimagen.jpg', upload_to='sitio/imagenes/'),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='foto_general',
            field=models.ImageField(default='/static/sitio/imagenes/turismo_noimagen.jpg', upload_to='sitio/imagenes/'),
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='foto_perfil',
            field=models.ImageField(default='/static/sitio/imagenes/turismo_noimagen.jpg', upload_to='sitio/imagenes/'),
        ),
    ]
