# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_auto_20170521_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='calificacion',
            field=models.CharField(choices=[('Malo', 'Malo'), ('Regular', 'Regular'), ('Bueno', 'Bueno'), ('Muy Bueno', 'Muy Bueno'), ('Excelente', 'Excelente')], default='Bueno', max_length=9),
        ),
    ]
