# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_auto_20170523_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntaje',
            name='puntos',
            field=models.CharField(choices=[('Malo', 'Malo'), ('Regular', 'Regular'), ('Bueno', 'Bueno'), ('Muy Bueno', 'Muy Bueno'), ('Excelente', 'Excelente')], default='Bueno', max_length=9),
        ),
    ]
