# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0013_auto_20170523_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntaje',
            name='puntos',
        ),
        migrations.AddField(
            model_name='puntaje',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], default=3, max_length=1),
        ),
    ]
