# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0014_auto_20170524_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntaje',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 'Malo'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], default=3),
        ),
    ]
