# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0018_auto_20170524_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='localidad',
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
    ]
