# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0024_auto_20170526_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariosdenunciados',
            name='url_comentario',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerariosdenunciados',
            name='url_itinerario',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
