# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0025_auto_20170612_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentariosdenunciados',
            name='url_comentario',
        ),
        migrations.RemoveField(
            model_name='itinerariosdenunciados',
            name='url_itinerario',
        ),
    ]
