# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0026_auto_20170612_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=20, null=True),
        ),
    ]
